# Generated by Django 5.1.2 on 2024-10-18 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_artist_artistregistration_artwork_customuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='artist_images/'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='artwork_image',
            field=models.ImageField(blank=True, null=True, upload_to='artwork_images/'),
        ),
    ]
