# Generated by Django 5.1.2 on 2024-10-18 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_artist_profile_image_artwork_artwork_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
