# Generated by Django 5.1.2 on 2024-10-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_artist_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='status',
            field=models.CharField(choices=[('P', '대기중'), ('A', '승인됨'), ('R', '거부됨')], default='P', max_length=1),
        ),
        migrations.DeleteModel(
            name='ArtistRegistration',
        ),
    ]
